include:
  - project: adeotech/lmfr/turbine/turbine-gitlab-ci-lib
    file: /turbine-internals/base-build.yml

variables:
  GITHUB_URL: git@github.com:adeo/turbine-go-api-skeleton.git
  TURBINE_COMPONENT_NAME: turbine-go-api-skeleton

